/**
 * Comprehensive List of Reserved, System, Protocol, and Sensitive Subdomains.
 * Based on RFC Standards (RFC 2142, RFC 2606, RFC 6761, RFC 8615),
 * Open-source security industry standards (shouldbee/reserved-usernames),
 * and SaaS Enterprise Brand Protection Best Practices (Anti-Squatting / Anti-Impersonation).
 *
 * Prevents users from registering subdomains that conflict with platform infrastructure,
 * administrative tools, security services, national institutions, payment gateways,
 * or unauthorized trademark squatting.
 */

export const SYSTEM_RESERVED_SUBDOMAINS: Set<string> = new Set([
  // =========================================================================
  // 1. Core Platform & App Routes
  // =========================================================================
  "dzmenu",
  "dz-menu",
  "dz_menu",
  "menu",
  "menus",
  "app",
  "apps",
  "application",
  "applications",
  "web",
  "www",
  "www1",
  "www2",
  "www3",
  "root",
  "main",
  "home",
  "index",
  "default",
  "core",
  "base",
  "hub",
  "portal",
  "platform",
  "site",
  "sites",
  "page",
  "pages",

  // =========================================================================
  // 2. Authentication, Security, Cryptography & IAM
  // =========================================================================
  "admin",
  "admins",
  "admen",
  "administrator",
  "administrators",
  "superadmin",
  "super-admin",
  "rootadmin",
  "sysadmin",
  "sys-admin",
  "netadmin",
  "dbadmin",
  "webmaster",
  "hostmaster",
  "postmaster",
  "cpanel",
  "whm",
  "mod",
  "moderator",
  "moderators",
  "owner",
  "master",
  "sys",
  "system",
  "security",
  "secure",
  "safety",
  "trust",
  "auth",
  "auth0",
  "authenticate",
  "authentication",
  "authorize",
  "authorization",
  "login",
  "signin",
  "log-in",
  "sign-in",
  "logout",
  "signout",
  "log-out",
  "sign-out",
  "signup",
  "register",
  "registration",
  "sign-up",
  "join",
  "invite",
  "invitation",
  "invites",
  "oauth",
  "oauth2",
  "sso",
  "saml",
  "openid",
  "2fa",
  "mfa",
  "otp",
  "magic",
  "magiclink",
  "magic-link",
  "verify",
  "verification",
  "confirm",
  "confirmation",
  "validate",
  "session",
  "sessions",
  "token",
  "tokens",
  "jwt",
  "key",
  "keys",
  "secret",
  "secrets",
  "vault",
  "cert",
  "certs",
  "certificate",
  "certificates",
  "ssl",
  "tls",
  "ssh",
  "gpg",
  "pgp",
  "password",
  "passwords",
  "passwd",
  "reset-password",
  "forgot-password",
  "recover",
  "recovery",
  "account",
  "accounts",
  "user",
  "users",
  "profile",
  "profiles",
  "member",
  "members",
  "membership",
  "guest",
  "guests",
  "anonymous",
  "anon",
  "impersonate",
  "sudo",
  "su",

  // =========================================================================
  // 3. API, Developers, Webhooks, Integrations & RPC
  // =========================================================================
  "api",
  "apis",
  "v1",
  "v2",
  "v3",
  "v4",
  "rest",
  "graphql",
  "graph",
  "gql",
  "rpc",
  "grpc",
  "json",
  "xml",
  "feed",
  "feeds",
  "rss",
  "atom",
  "sdk",
  "sdks",
  "dev",
  "devel",
  "developer",
  "developers",
  "development",
  "doc",
  "docs",
  "documentation",
  "spec",
  "specs",
  "swagger",
  "openapi",
  "postman",
  "sandbox",
  "playground",
  "console",
  "terminal",
  "cli",
  "tool",
  "tools",
  "webhook",
  "webhooks",
  "hook",
  "hooks",
  "callback",
  "callbacks",
  "event",
  "events",
  "stream",
  "streams",
  "socket",
  "sockets",
  "ws",
  "wss",
  "connect",
  "connection",
  "integration",
  "integrations",
  "partner",
  "partners",
  "affiliate",
  "affiliates",
  "plugin",
  "plugins",
  "extension",
  "extensions",
  "addon",
  "addons",
  "marketplace",

  // =========================================================================
  // 4. Infrastructure, DevOps, Cloud & Networking
  // =========================================================================
  "server",
  "servers",
  "host",
  "hosts",
  "hosting",
  "cluster",
  "node",
  "nodes",
  "edge",
  "cloud",
  "infra",
  "infrastructure",
  "k8s",
  "kubernetes",
  "docker",
  "swarm",
  "container",
  "containers",
  "vm",
  "vms",
  "dns",
  "dns1",
  "dns2",
  "ns",
  "ns1",
  "ns2",
  "ns3",
  "ns4",
  "soa",
  "mx",
  "mx1",
  "mx2",
  "ptr",
  "cname",
  "txt",
  "dhcp",
  "router",
  "gateway",
  "proxy",
  "proxies",
  "reverse-proxy",
  "lb",
  "loadbalancer",
  "balancer",
  "traefik",
  "nginx",
  "apache",
  "caddy",
  "envoy",
  "ingress",
  "vpn",
  "wireguard",
  "openvpn",
  "ipsec",
  "tunnel",
  "cdn",
  "assets",
  "asset",
  "static",
  "media",
  "image",
  "images",
  "img",
  "imgs",
  "photo",
  "photos",
  "pic",
  "pics",
  "video",
  "videos",
  "audio",
  "sound",
  "sounds",
  "font",
  "fonts",
  "css",
  "js",
  "javascript",
  "files",
  "file",
  "download",
  "downloads",
  "upload",
  "uploads",
  "s3",
  "blob",
  "bucket",
  "buckets",
  "storage",
  "cache",
  "redis",
  "memcached",
  "database",
  "db",
  "sql",
  "mysql",
  "postgres",
  "postgresql",
  "mongo",
  "mongodb",
  "supabase",
  "prisma",

  // =========================================================================
  // 5. Email, Messaging & Communications Protocols (RFC 2142)
  // =========================================================================
  "mail",
  "email",
  "e-mail",
  "mailbox",
  "mailman",
  "postfix",
  "sendmail",
  "exim",
  "smtp",
  "imap",
  "imap4",
  "pop",
  "pop3",
  "webmail",
  "postmaster",
  "hostmaster",
  "usenet",
  "news",
  "nntp",
  "ftp",
  "sftp",
  "ftps",
  "tftp",
  "telnet",
  "irc",
  "chat",
  "sms",
  "mms",
  "voip",
  "sip",
  "xmpp",
  "jabber",
  "matrix",
  "notify",
  "notification",
  "notifications",
  "alert",
  "alerts",
  "broadcast",
  "newsletter",
  "bounce",
  "bounces",
  "abuse",
  "spam",
  "phishing",

  // =========================================================================
  // 6. Monitoring, Telemetry, Observability & Analytics
  // =========================================================================
  "status",
  "uptime",
  "health",
  "healthz",
  "ping",
  "pong",
  "heartbeat",
  "live",
  "ready",
  "readyz",
  "metrics",
  "metric",
  "telemetry",
  "monitor",
  "monitoring",
  "stats",
  "statistics",
  "analytics",
  "tracking",
  "tracker",
  "grafana",
  "prometheus",
  "datadog",
  "sentry",
  "elastic",
  "elasticsearch",
  "log",
  "logs",
  "logging",
  "kibana",
  "audit",
  "auditing",

  // =========================================================================
  // 7. Environments, Stages & CI/CD Pipelines
  // =========================================================================
  "prod",
  "production",
  "stage",
  "staging",
  "test",
  "testing",
  "tests",
  "qa",
  "uat",
  "local",
  "localhost",
  "internal",
  "intranet",
  "corp",
  "private",
  "preview",
  "demo",
  "canary",
  "alpha",
  "beta",
  "rc",
  "nightly",
  "ci",
  "cd",
  "pipeline",
  "build",
  "builds",
  "jenkins",
  "gitlab",
  "github",
  "deploy",
  "deployment",
  "deployments",
  "release",
  "releases",
  "version",

  // =========================================================================
  // 8. Billing, Payments, FinTech & Subscriptions
  // =========================================================================
  "billing",
  "bill",
  "bills",
  "invoice",
  "invoices",
  "receipt",
  "receipts",
  "payment",
  "payments",
  "pay",
  "checkout",
  "cart",
  "basket",
  "order",
  "orders",
  "pricing",
  "price",
  "plan",
  "plans",
  "subscription",
  "subscriptions",
  "subscribe",
  "upgrade",
  "renew",
  "renewal",
  "wallet",
  "wallets",
  "credit",
  "debit",
  "bank",
  "banking",
  "finance",
  "financial",
  "accounting",
  "tax",
  "taxes",
  "vat",
  "refund",
  "refunds",

  // =========================================================================
  // 9. Payment Gateways & Banking Networks (Global & Algerian)
  // =========================================================================
  "chargily",
  "chargilypay",
  "satim",
  "cib",
  "edahabia",
  "poste",
  "algerieposte",
  "algerie-poste",
  "eccp",
  "baridimob",
  "baridi-mob",
  "baridinet",
  "banque",
  "bank",
  "bea",
  "bna",
  "bdl",
  "cpa",
  "badr",
  "cnep",
  "albaraka",
  "societegenerale",
  "natixis",
  "bnp",
  "bnpparibas",
  "stripe",
  "paypal",
  "visa",
  "mastercard",
  "amex",
  "americanexpress",
  "applepay",
  "googlepay",

  // =========================================================================
  // 10. Algerian Sovereign, Institutional, Telecom & Emergency Services
  // =========================================================================
  "algeria",
  "algerie",
  "dz",
  "el-mouradia",
  "presidence",
  "premier-ministre",
  "gouvernement",
  "ministere",
  "douane",
  "douanes",
  "impots",
  "police",
  "dgsn",
  "gendarmerie",
  "gn",
  "protection-civile",
  "pompiers",
  "defense",
  "mdn",
  "justice",
  "sante",
  "commerce",
  "education",
  "wilaya",
  "daira",
  "commune",
  "apc",
  "apw",

  // =========================================================================
  // 11. Support, Helpdesk, Legal & Corporate Terms
  // =========================================================================
  "help",
  "support",
  "helpdesk",
  "service",
  "services",
  "faq",
  "guide",
  "guides",
  "tutorial",
  "tutorials",
  "contact",
  "contactus",
  "contact-us",
  "feedback",
  "about",
  "aboutus",
  "about-us",
  "blog",
  "news",
  "press",
  "media-kit",
  "careers",
  "career",
  "jobs",
  "job",
  "hiring",
  "legal",
  "terms",
  "tos",
  "privacy",
  "policy",
  "compliance",
  "gdpr",
  "copyright",
  "dmca",
  "trademark",
  "patent",
  "license",
  "investors",
  "ir",
  "corporate",
  "hq",
  "office",
  "official",
  "verified",
]);

export const PROTECTED_BRAND_SUBDOMAINS: Set<string> = new Set([
  // =========================================================================
  // 12. Global Fast Food, Dining & Cafe Franchises (Anti-Squatting Protection)
  // =========================================================================
  "mcdonalds",
  "mcdonald",
  "mcd",
  "kfc",
  "kentucky",
  "burgerking",
  "burger-king",
  "bk",
  "subway",
  "starbucks",
  "starbuck",
  "pizzahut",
  "pizza-hut",
  "dominos",
  "domino-pizza",
  "dunkin",
  "dunkindonuts",
  "dunkin-donuts",
  "wendys",
  "wendy",
  "hardees",
  "hardee",
  "papajohns",
  "papa-johns",
  "fiveguys",
  "five-guys",
  "shakeshack",
  "shake-shack",
  "innout",
  "in-n-out",
  "chipotle",
  "tacobell",
  "taco-bell",
  "popeyes",
  "popeye",
  "nandos",
  "nando",
  "cinnabon",
  "krispykreme",
  "krispy-kreme",
  "timhortons",
  "tim-hortons",
  "costa",
  "costacoffee",
  "costa-coffee",
  "baskinrobbins",
  "baskin-robbins",
  "haagendazs",
  "haagen-dazs",
  "paul",
  "paul-bakery",
  "briochedoree",
  "brioche-doree",
  "le-pain-quotidien",
  "pretamanger",
  "pret-a-manger",

  // =========================================================================
  // 13. Prominent Algerian & Regional Restaurant Brands & Food Franchises
  // =========================================================================
  "elpadre",
  "el-padre",
  "padre",
  "underfood",
  "under-food",
  "wonderfood",
  "wonder-food",
  "quick",
  "quickalgerie",
  "quick-algerie",
  "o-tacos",
  "otacos",
  "chamas-tacos",
  "chamastacos",
  "tonton-burger",
  "tontonburger",
  "woodpecker",
  "chickano",
  "chickanos",
  "bando",
  "bando-burger",
  "planet-food",
  "planetfood",
  "casadelburger",
  "casa-del-burger",
  "alfuego",
  "al-fuego",
  "caracoya",
  "el-djenina",
  "eldjenina",
  "tantra",
  "le-lagon",
  "lelagon",
  "la-voile-d-or",
  "lavoiledor",
  "hippopotamus",
  "buffalo-grill",
  "courtepaille",

  // =========================================================================
  // 14. Prominent Food, Beverage & CPG Trademarks
  // =========================================================================
  "coca",
  "cocacola",
  "coca-cola",
  "pepsi",
  "pepsico",
  "redbull",
  "red-bull",
  "monster",
  "sevenup",
  "7up",
  "sprite",
  "fanta",
  "mirinda",
  "schweppes",
  "heineken",
  "nestle",
  "danone",
  "nutella",
  "ferrero",
  "kinder",
  "oreo",
  "mondelez",
  "unilever",
  "soummam",
  "toudja",
  "ifri",
  "cevital",
  "ngaous",
  "hamoud",
  "hamoudboualem",
  "hamoud-boualem",
  "rouiba",
  "ramy",
  "bimo",
  "amor-benamor",
  "benamor",
  "safina",
  "sim",

  // =========================================================================
  // 15. Algerian Telecoms & ISP Operators
  // =========================================================================
  "algerietelecom",
  "algerie-telecom",
  "mobilis",
  "djezzy",
  "ooredoo",
  "nedjma",
  "idoom",

  // =========================================================================
  // 16. Tech Giants, Social Media & Digital Platforms
  // =========================================================================
  "google",
  "facebook",
  "meta",
  "instagram",
  "tiktok",
  "twitter",
  "x",
  "youtube",
  "whatsapp",
  "telegram",
  "snapchat",
  "linkedin",
  "microsoft",
  "apple",
  "amazon",
  "netflix",
  "spotify",
  "discord",
  "zoom",
  "slack",

  // =========================================================================
  // 17. Delivery, Logistics, E-commerce & Retail Chains
  // =========================================================================
  "yalidine",
  "yalidine-express",
  "procolis",
  "kazitour",
  "zr-express",
  "zrexpress",
  "maystro",
  "maystro-delivery",
  "jumia",
  "jumia-food",
  "jumiafood",
  "yassir",
  "yassir-express",
  "yassirexpress",
  "yassirfood",
  "coursa",
  "heetch",
  "uber",
  "ubereats",
  "uber-eats",
  "deliveroo",
  "glovo",
  "talabat",
  "careem",
  "doordash",
  "door-dash",
  "grubhub",
  "justeat",
  "just-eat",
  "foodpanda",
  "wolt",
  "carrefour",
  "auchan",
  "uno",
  "monoprix",
  "lidl",
  "aldi",
  "walmart",
  "costco",
  "target",
  "ikea",
  "decathlon",
  "aliexpress",
  "ali-express",
  "alibaba",
  "temu",
  "shein",
]);

// Combined Set for generic checks
export const RESERVED_SUBDOMAINS: Set<string> = new Set([
  ...SYSTEM_RESERVED_SUBDOMAINS,
  ...PROTECTED_BRAND_SUBDOMAINS,
]);

export interface SubdomainValidationResult {
  isValid: boolean;
  status: "AVAILABLE" | "INVALID_LENGTH" | "INVALID_FORMAT" | "SYSTEM_RESERVED" | "PROTECTED_BRAND" | "CONSECUTIVE_HYPHENS";
  message: string;
  canClaim?: boolean;
}

/**
 * Validates whether a requested subdomain meets naming rules and handles system vs brand protection.
 * - Allowed length: 3 to 30 characters
 * - Characters: lowercase alphanumeric (a-z, 0-9) and hyphens (-)
 * - Cannot start or end with a hyphen
 * - No consecutive hyphens (e.g., 'foo--bar')
 * - SYSTEM_RESERVED_SUBDOMAINS: Infrastructure keywords, strictly blocked.
 * - PROTECTED_BRAND_SUBDOMAINS: Trademark protection, claimable via official corporate email.
 */
export function validateSubdomain(subdomain: string): SubdomainValidationResult {
  const normalized = (subdomain || "").trim().toLowerCase();

  // Length check (3 to 30 chars)
  if (normalized.length < 3 || normalized.length > 30) {
    return {
      isValid: false,
      status: "INVALID_LENGTH",
      message: "Subdomain must be between 3 and 30 characters.",
    };
  }

  // Allowed characters: lowercase a-z, numbers 0-9, and hyphens (cannot start or end with a hyphen)
  const regex = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;
  if (!regex.test(normalized)) {
    return {
      isValid: false,
      status: "INVALID_FORMAT",
      message: "Only lowercase letters (a-z), numbers (0-9), and hyphens (-) are allowed.",
    };
  }

  // Consecutive hyphens check (e.g., 'foo--bar')
  if (normalized.includes("--")) {
    return {
      isValid: false,
      status: "CONSECUTIVE_HYPHENS",
      message: "Consecutive hyphens (--) are not permitted.",
    };
  }

  // 1. System Keyword Check (Platform infrastructure)
  if (SYSTEM_RESERVED_SUBDOMAINS.has(normalized)) {
    return {
      isValid: false,
      status: "SYSTEM_RESERVED",
      message: "This subdomain is reserved for platform infrastructure.",
      canClaim: false,
    };
  }

  // 2. Protected Brand Check (Trademarks & franchises)
  if (PROTECTED_BRAND_SUBDOMAINS.has(normalized)) {
    return {
      isValid: false,
      status: "PROTECTED_BRAND",
      message: "This name belongs to a protected brand. Official representatives can claim it.",
      canClaim: true,
    };
  }

  return {
    isValid: true,
    status: "AVAILABLE",
    message: "Subdomain is valid and available.",
  };
}
