import type {
  ThemePresetDefinition,
  ThemePresetId,
  ThemeSettingControl,
  SectionDefinition,
} from "@/types/theme-engine";

export const COMMON_THEME_CONTROLS: ThemeSettingControl[] = [
  // Colors Category
  {
    id: "colors.primary",
    label: "Primary Brand Color",
    type: "color",
    category: "colors",
    defaultValue: "#D97706",
  },
  {
    id: "colors.accent",
    label: "Accent / Glow Color",
    type: "color",
    category: "colors",
    defaultValue: "#F59E0B",
  },
  {
    id: "colors.background",
    label: "Background Color",
    type: "color",
    category: "colors",
    defaultValue: "#FAF9F5",
  },
  {
    id: "colors.surface",
    label: "Card Surface Color",
    type: "color",
    category: "colors",
    defaultValue: "#FFFFFF",
  },
  {
    id: "colors.text",
    label: "Text Color",
    type: "color",
    category: "colors",
    defaultValue: "#18181B",
  },

  // Typography Category
  {
    id: "typography.font_family",
    label: "Font Family",
    type: "font",
    category: "typography",
    defaultValue: "Outfit",
    options: [
      { label: "Outfit (Modern Clean)", value: "Outfit" },
      { label: "Inter (Tech Minimal)", value: "Inter" },
      { label: "Playfair Display (Luxury Serif)", value: "Playfair Display" },
      { label: "Cairo (Arabic Standard)", value: "Cairo" },
      { label: "Tajawal (Arabic Modern)", value: "Tajawal" },
    ],
  },
  {
    id: "typography.heading_weight",
    label: "Heading Weight",
    type: "select",
    category: "typography",
    defaultValue: "bold",
    options: [
      { label: "Regular", value: "normal" },
      { label: "Medium", value: "medium" },
      { label: "Bold", value: "bold" },
      { label: "Black", value: "black" },
    ],
  },

  // Layout Category
  {
    id: "layout.category_style",
    label: "Category Navigation Style",
    type: "select",
    category: "layout",
    defaultValue: "stories",
    options: [
      { label: "1. Circle Style (Stories)", value: "stories" },
      { label: "4. Minimal Icon Style", value: "minimal_icons" },
      { label: "8. Card with Badge Style", value: "card_badges" },
      { label: "9. Modern Glass Style", value: "glass" },
      { label: "3. Banner Showcase Style", value: "banner" },
    ],
  },
  {
    id: "layout.card_style",
    label: "Dish Card Display",
    type: "select",
    category: "layout",
    defaultValue: "hero",
    options: [
      { label: "Hero Card (Large Image & Description)", value: "hero" },
      { label: "2-Column Fast Grid", value: "grid_2col" },
      { label: "Compact Horizontal Rows", value: "compact_row" },
    ],
  },
  {
    id: "layout.show_header_banner",
    label: "Show Cover Banner Header",
    type: "boolean",
    category: "layout",
    defaultValue: true,
  },
  {
    id: "layout.show_all_category",
    label: "Show 'All' Category",
    type: "boolean",
    category: "layout",
    defaultValue: true,
  },
  {
    id: "layout.show_cart_bar",
    label: "Show Floating Order Cart Bar",
    type: "boolean",
    category: "layout",
    defaultValue: true,
  },
  {
    id: "layout.show_search",
    label: "Show Quick Search Bar",
    type: "boolean",
    category: "layout",
    defaultValue: true,
  },
];

export const COMMON_SUPPORTED_SECTIONS: SectionDefinition[] = [
  {
    type: "restaurant-header",
    name: "Restaurant Header & Cover",
    isUnique: true,
    supportedBlocks: ["wifi-badge", "hours-badge", "social-links"],
    settings: [
      {
        id: "show_cover",
        label: "Display Cover Image",
        type: "boolean",
        category: "layout",
        defaultValue: true,
      },
      {
        id: "show_status_badge",
        label: "Display Open / Closed Badge",
        type: "boolean",
        category: "layout",
        defaultValue: true,
      },
    ],
  },
  {
    type: "promo-banner",
    name: "Promotional Banner / Hero Offer",
    isUnique: true,
    supportedBlocks: ["action-button"],
    settings: [
      {
        id: "banner_text",
        label: "Promo Heading",
        type: "select",
        category: "layout",
        defaultValue: "Special Deal",
      },
    ],
  },
  {
    type: "category-bar",
    name: "Category Navigation Bar",
    isUnique: true,
    supportedBlocks: [],
    settings: [],
  },
  {
    type: "menu-body",
    name: "Menu Items & Dishes Grid",
    isUnique: true,
    supportedBlocks: [],
    settings: [],
  },
  {
    type: "floating-cart",
    name: "Sticky Bottom Cart / Order Bar",
    isUnique: true,
    supportedBlocks: [],
    settings: [],
  },
];

export const THEME_DEFINITIONS: Record<ThemePresetId, ThemePresetDefinition> = {
  gourmet: {
    presetId: "gourmet",
    name: "Gourmet",
    tagline: "Warm Luxury & Fine Dining",
    description: "Designed for fine dining, steak houses, and upscale bistros with warm golden amber tones, story avatars, and premium hero dish cards.",
    author: "by DZMenu",
    previewImage: "/images/themes/gourmet.svg",
    defaultSettings: {
      paletteId: "original",
      typography: {
        font_family: "Outfit",
        heading_weight: "bold",
        base_font_size: 16,
      },
      layout: {
        category_style: "stories",
        card_style: "hero",
        show_header_banner: true,
        show_all_category: true,
        show_cart_bar: true,
        show_search: true,
        card_radius: 16,
      },
      image_slots: {},
    },
    defaultSections: [
      {
        id: "header_01",
        type: "restaurant-header",
        enabled: true,
        settings: { show_cover: true, show_status_badge: true },
        blocks: [{ id: "b_wifi", type: "wifi-badge", settings: { style: "pill" } }],
      },
      {
        id: "cat_01",
        type: "category-bar",
        enabled: true,
        settings: { style: "stories" },
        blocks: [],
      },
      {
        id: "body_01",
        type: "menu-body",
        enabled: true,
        settings: { card_style: "hero" },
        blocks: [],
      },
      {
        id: "cart_01",
        type: "floating-cart",
        enabled: true,
        settings: { style: "gold" },
        blocks: [],
      },
    ],
    controls: COMMON_THEME_CONTROLS,
    supportedSections: COMMON_SUPPORTED_SECTIONS,
    supportedBlocks: {
      "wifi-badge": {
        type: "wifi-badge",
        name: "Wi-Fi Badge",
        settings: [],
      },
      "hours-badge": {
        type: "hours-badge",
        name: "Operating Hours Badge",
        settings: [],
      },
    },
  },

  craving: {
    presetId: "craving",
    name: "Craving",
    tagline: "Bold High Energy & Fast Casual",
    description: "Appetite-triggering red and blazing yellow energy with 2-column fast food cards, badge category tabs, and promo banners.",
    author: "by DZMenu",
    previewImage: "/images/themes/craving.svg",
    defaultSettings: {
      paletteId: "blaze_red",
      typography: {
        font_family: "Outfit",
        heading_weight: "black",
        base_font_size: 16,
      },
      layout: {
        category_style: "card_badges",
        card_style: "grid_2col",
        card_radius: 18,
        show_header_banner: true,
        show_all_category: true,
        show_cart_bar: true,
        show_search: true,
        show_promo_banner: true,
      },
      image_slots: {},
    },
    defaultSections: [
      {
        id: "header_01",
        type: "restaurant-header",
        enabled: true,
        settings: { show_cover: true, show_status_badge: true },
        blocks: [],
      },
      {
        id: "cat_01",
        type: "category-bar",
        enabled: true,
        settings: { style: "card_badges" },
        blocks: [],
      },
      {
        id: "body_01",
        type: "menu-body",
        enabled: true,
        settings: { card_style: "grid_2col" },
        blocks: [],
      },
      {
        id: "cart_01",
        type: "floating-cart",
        enabled: true,
        settings: { style: "bold_red" },
        blocks: [],
      },
    ],
    controls: COMMON_THEME_CONTROLS,
    supportedSections: COMMON_SUPPORTED_SECTIONS,
    supportedBlocks: {},
  },

  crema: {
    presetId: "crema",
    name: "Crema",
    tagline: "Earthy Warmth & Specialty Coffee",
    description: "Subtle terracotta, velvety cream backgrounds, and clean compact rows designed for bakeries, brunch spots, and artisan cafés.",
    author: "by DZMenu",
    previewImage: "/images/themes/crema.svg",
    defaultSettings: {
      paletteId: "rose_patisserie",
      splash: {
        enabled: true,
        title: "Sweet Moments",
        subtitle: "DESSERTS & CAFÉ",
        auto_dismiss_seconds: 2.5,
      },
      greeting: {
        title: "Hello",
        morning_subtitle: "Good Morning",
        evening_subtitle: "Good Evening",
      },
      typography: {
        font_family: "Playfair Display",
        heading_weight: "bold",
        base_font_size: 16,
      },
      layout: {
        category_style: "minimal_icons",
        card_style: "cafe_grid",
        card_radius: 22,
        show_header_banner: true,
        show_all_category: false,
        show_search: true,
      },
      image_slots: {},
    },
    defaultSections: [
      {
        id: "header_01",
        type: "restaurant-header",
        enabled: true,
        settings: { show_cover: true, show_status_badge: true },
        blocks: [{ id: "b_wifi", type: "wifi-badge", settings: {} }],
      },
      {
        id: "cat_01",
        type: "category-bar",
        enabled: true,
        settings: { style: "minimal_icons" },
        blocks: [],
      },
      {
        id: "body_01",
        type: "menu-body",
        enabled: true,
        settings: { card_style: "cafe_grid" },
        blocks: [],
      },
      {
        id: "cart_01",
        type: "floating-cart",
        enabled: true,
        settings: { style: "mocha" },
        blocks: [],
      },
    ],
    controls: COMMON_THEME_CONTROLS,
    supportedSections: COMMON_SUPPORTED_SECTIONS,
    supportedBlocks: {},
  },

  noir: {
    presetId: "noir",
    name: "Noir",
    tagline: "Sleek Glassmorphism & Cocktail Lounges",
    description: "Deep obsidian backdrop with neon amber reflections, frosted glass category tabs, and high-contrast photography showcase.",
    author: "by DZMenu",
    previewImage: "/images/themes/noir.svg",
    defaultSettings: {
      paletteId: "obsidian_gold",
      typography: {
        font_family: "Inter",
        heading_weight: "bold",
        base_font_size: 16,
      },
      layout: {
        category_style: "glass",
        card_style: "cinematic_hero",
        card_radius: 20,
        show_header_banner: true,
        show_all_category: true,
        show_cart_bar: true,
        show_search: true,
      },
      image_slots: {},
    },
    defaultSections: [
      {
        id: "header_01",
        type: "restaurant-header",
        enabled: true,
        settings: { show_cover: true, show_status_badge: true },
        blocks: [],
      },
      {
        id: "cat_01",
        type: "category-bar",
        enabled: true,
        settings: { style: "glass" },
        blocks: [],
      },
      {
        id: "body_01",
        type: "menu-body",
        enabled: true,
        settings: { card_style: "cinematic_hero" },
        blocks: [],
      },
      {
        id: "cart_01",
        type: "floating-cart",
        enabled: true,
        settings: { style: "neon_glow" },
        blocks: [],
      },
    ],
    controls: COMMON_THEME_CONTROLS,
    supportedSections: COMMON_SUPPORTED_SECTIONS,
    supportedBlocks: {},
  },

  basil: {
    presetId: "basil",
    name: "Basil",
    tagline: "Fresh Organic & Woodfired Italian",
    description: "Crisp emerald botanical tones and rustic Italian warmth that celebrate organic bowls, salads, and authentic artisan pizza.",
    author: "by DZMenu",
    previewImage: "/images/themes/basil.svg",
    defaultSettings: {
      paletteId: "toscana_olive",
      typography: {
        font_family: "Outfit",
        heading_weight: "bold",
        base_font_size: 16,
      },
      layout: {
        category_style: "banner",
        card_style: "artisan_card",
        card_radius: 18,
        show_header_banner: true,
        show_all_category: true,
        show_cart_bar: true,
        show_search: true,
      },
      image_slots: {},
    },
    defaultSections: [
      {
        id: "header_01",
        type: "restaurant-header",
        enabled: true,
        settings: { show_cover: true, show_status_badge: true },
        blocks: [],
      },
      {
        id: "cat_01",
        type: "category-bar",
        enabled: true,
        settings: { style: "banner" },
        blocks: [],
      },
      {
        id: "body_01",
        type: "menu-body",
        enabled: true,
        settings: { card_style: "artisan_card" },
        blocks: [],
      },
      {
        id: "cart_01",
        type: "floating-cart",
        enabled: true,
        settings: { style: "botanical_green" },
        blocks: [],
      },
    ],
    controls: COMMON_THEME_CONTROLS,
    supportedSections: COMMON_SUPPORTED_SECTIONS,
    supportedBlocks: {},
  },
};
